CREATE TABLE file (
    id SERIAL PRIMARY KEY,
    name VARCHAR NOT NULL,
    path VARCHAR NOT NULL,
    car_id INT,
    CONSTRAINT CAR_ID_FK FOREIGN KEY (car_id) REFERENCES car(id) ON DELETE CASCADE
);